/* Generated by Cython 3.0.12 */

#ifndef __PYX_HAVE__pyasio
#define __PYX_HAVE__pyasio

#include "Python.h"
struct ASIODriverInfo;
typedef struct ASIODriverInfo ASIODriverInfo;

/* "pyasio.pxd":107
 *     ASIOTime* (*bufferSwitchTimeInfo)(ASIOTime* params, long doubleBufferIndex, ASIOBool directProcess)
 * 
 * ctypedef public struct ASIODriverInfo:             # <<<<<<<<<<<<<<
 *     long asioVersion
 *     long driverVersion
 */
struct ASIODriverInfo {
  long asioVersion;
  long driverVersion;
  char name[32];
  char errorMessage[0x7C];
  void *sysRef;
};

#ifndef __PYX_HAVE_API__pyasio

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
    #define __PYX_EXTERN_C extern "C++"
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

#endif /* !__PYX_HAVE_API__pyasio */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpyasio(void);
#else
/* WARNING: Use PyImport_AppendInittab("pyasio", PyInit_pyasio) instead of calling PyInit_pyasio directly from Python 3.5 */
PyMODINIT_FUNC PyInit_pyasio(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"pyasio\", PyInit_pyasio) instead of calling PyInit_pyasio directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"pyasio\", PyInit_pyasio) instead of calling PyInit_pyasio directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"pyasio\", PyInit_pyasio) instead of calling PyInit_pyasio directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_pyasio_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_pyasio() __PYX_WARN_IF_PyInit_pyasio_INIT_CALLED(PyInit_pyasio())
#endif
#endif

#endif /* !__PYX_HAVE__pyasio */
